apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-time-gui
  namespace: app-time
spec:
  selector:
    matchLabels:
      app: app-time-gui
  template:
    metadata:
      labels:
        app: app-time-gui
        namespace: app-time
    spec:
      containers:
      - name: app-time-gui
        image: simoncarr/sample-app-time-gui
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
